// Ported from warehouse/Sources by tools/port_warehouse.py so the worker app
// carries the warehouse itself. The standalone warehouse app is unchanged;
// see worker/README.md for how the two relate.

// Generated from PanelVault's component catalog — do not edit by hand.
// Regenerate with scratchpad/gen_warehouse_catalog.py whenever PanelVault's
// ComponentGroup.samples changes. Part ids must stay identical across both
// apps: they are the key that links warehouse stock to boards.

import Foundation

// Codable so user-created custom parts can persist alongside catalog ones.
struct CatalogPart: Identifiable, Hashable, Codable {
  let id: String
  let manufacturer: String
  let type: String
  let model: String
  let rating: String
  let poles: String
  let curve: String
  let about: String
  /// Optional manufacturer serial number for a specific/custom component.
  /// Catalog families leave this nil because they describe a product line.
  var serialNumber: String? = nil

  var displayName: String {
    "\(manufacturer) \(model)"
  }

  var searchText: String {
    "\(manufacturer) \(type) \(model) \(rating) \(poles) \(curve) \(serialNumber ?? "")".lowercased()
  }
}

struct CatalogGroup: Identifiable {
  let id: String
  let name: String
  let parts: [CatalogPart]
}

enum Catalog {
  static func part(for id: String) -> CatalogPart? {
    partsByID[id]
  }

  static let allParts: [CatalogPart] = groups.flatMap(\.parts)

  static let partsByID: [String: CatalogPart] =
    Dictionary(uniqueKeysWithValues: allParts.map { ($0.id, $0) })

  static let groups: [CatalogGroup] = [
    CatalogGroup(id: "mcbs", name: "MCBs", parts: [
      CatalogPart(id: "abb-s201-1p", manufacturer: "ABB", type: "MCB", model: "S201", rating: "Set A", poles: "1P", curve: "B/C/D Curve", about: "Single-pole miniature circuit breaker for one final circuit, protecting against overload and short circuit. Pick the curve for the load: B for resistive and lighting, C for general mixed loads, D for high-inrush motors and transformers."),
      CatalogPart(id: "abb-s202-2p", manufacturer: "ABB", type: "MCB", model: "S202", rating: "Set A", poles: "2P", curve: "B/C/D Curve", about: "Two-pole MCB that breaks line and neutral together, common on single-phase circuits where full isolation is required for maintenance."),
      CatalogPart(id: "abb-s203-3p", manufacturer: "ABB", type: "MCB", model: "S203", rating: "Set A", poles: "3P", curve: "B/C/D Curve", about: "Three-pole MCB for three-phase loads. All three poles trip together so a fault on one phase cannot leave a motor running single-phased."),
      CatalogPart(id: "abb-s204-4p", manufacturer: "ABB", type: "MCB", model: "S204", rating: "Set A", poles: "4P", curve: "B/C/D Curve", about: "Four-pole MCB breaking three phases plus neutral, used where the neutral must be isolated, such as on generator or changeover circuits."),
      CatalogPart(id: "abb-sn201-1pn", manufacturer: "ABB", type: "MCB", model: "SN201", rating: "Set A", poles: "1P+N", curve: "B/C Curve", about: "One pole plus switched neutral in a single module width, the usual choice for apartment and lighting boards where DIN space is tight."),
      CatalogPart(id: "abb-s300-p", manufacturer: "ABB", type: "MCB", model: "S300 P", rating: "Set A", poles: "1P-4P", curve: "Industrial", about: "Industrial-grade MCB with a higher breaking capacity than domestic ranges. Specify where the prospective short-circuit current at the board exceeds what a standard 6kA device can clear."),
      CatalogPart(id: "abb-su200", manufacturer: "ABB", type: "MCB", model: "SU200", rating: "Set A", poles: "1P-4P", curve: "UL/CSA", about: "MCB built to UL and CSA ratings for panels destined for North American markets or for machinery exported there."),
      CatalogPart(id: "schneider-ic60n", manufacturer: "Schneider", type: "MCB", model: "Acti9 iC60N", rating: "Set A", poles: "1P-4P", curve: "B/C/D", about: "Standard Acti9 MCB at 6kA breaking capacity, suitable for most commercial final circuits. Pairs with Vigi add-on blocks if earth-leakage protection is needed later."),
      CatalogPart(id: "schneider-ic60h", manufacturer: "Schneider", type: "MCB", model: "Acti9 iC60H", rating: "Set A", poles: "1P-4P", curve: "B/C/D", about: "Higher breaking capacity version of the iC60 for boards closer to the transformer where fault levels are greater."),
      CatalogPart(id: "siemens-5sy", manufacturer: "Siemens", type: "MCB", model: "SENTRON 5SY", rating: "Set A", poles: "1P-4P", curve: "B/C/D", about: "General purpose SENTRON MCB for final circuit protection across lighting, socket and small power circuits."),
      CatalogPart(id: "siemens-5sl", manufacturer: "Siemens", type: "MCB", model: "SENTRON 5SL", rating: "Set A", poles: "1P-4P", curve: "B/C/D", about: "Compact economy MCB for high-volume repeat circuits in residential and light commercial boards."),
      CatalogPart(id: "eaton-faz", manufacturer: "Eaton", type: "MCB", model: "FAZ", rating: "Set A", poles: "1P-4P", curve: "B/C/D", about: "Eaton MCB range with a wide curve and rating selection, frequently specified in machine-building and OEM panels.")
    ]),
    CatalogGroup(id: "rcbo", name: "RCBOs & RCDs", parts: [
      CatalogPart(id: "abb-ds201-1pn", manufacturer: "ABB", type: "RCBO", model: "DS201", rating: "Set A", poles: "1P+N", curve: "B/C Curve + RCD", about: "Combined MCB and residual current device in one module: overload, short-circuit and earth-leakage protection for a single circuit. Common at 30mA for socket outlets requiring additional protection."),
      CatalogPart(id: "abb-ds202-2p", manufacturer: "ABB", type: "RCBO", model: "DS202", rating: "Set A", poles: "2P", curve: "B/C Curve + RCD", about: "Two-pole RCBO providing overcurrent and earth-leakage protection while isolating both line and neutral."),
      CatalogPart(id: "abb-ds203-3p", manufacturer: "ABB", type: "RCBO", model: "DS203", rating: "Set A", poles: "3P", curve: "B/C Curve + RCD", about: "Three-pole RCBO for three-phase circuits needing residual current protection without a separate upstream RCCB."),
      CatalogPart(id: "abb-ds204-4p", manufacturer: "ABB", type: "RCBO", model: "DS204", rating: "Set A", poles: "4P", curve: "B/C Curve + RCD", about: "Four-pole RCBO covering three phases and neutral. Used where individual circuit discrimination matters more than a single shared RCCB."),
      CatalogPart(id: "abb-ds200", manufacturer: "ABB", type: "RCBO", model: "DS200", rating: "up to 63A", poles: "1P+N/3P+N", curve: "30-300mA, 10kA", about: "Higher breaking capacity RCBO range for boards with elevated fault levels where a standard 6kA device would be inadequate."),
      CatalogPart(id: "schneider-acti9-rcbo", manufacturer: "Schneider", type: "RCBO", model: "Acti9 iDPN Vigi", rating: "Set A", poles: "1P+N", curve: "B/C + RCD", about: "Acti9 RCBO in one module width, giving each circuit its own earth-leakage protection so a single fault does not trip an entire board section."),
      CatalogPart(id: "generic-rccb", manufacturer: "Generic", type: "RCD/RCCB", model: "Residual Current Device", rating: "Set A", poles: "2P/4P", curve: "30-300mA", about: "Residual current circuit breaker detecting earth leakage but offering no overload protection, so it always sits behind or above separate overcurrent devices. Choose the type by load: AC for simple resistive, A where electronics are present, B where drives or DC components can produce smooth residual currents."),
      CatalogPart(id: "abb-f200", manufacturer: "ABB", type: "RCD/RCCB", model: "F200", rating: "25-125A", poles: "2P/4P", curve: "30-500mA, Type AC/A", about: "Residual current circuit breaker protecting a group of circuits against earth leakage. At 30mA it provides additional protection against electric shock; at 300mA it is normally used for fire protection on a whole section."),
      CatalogPart(id: "schneider-iid", manufacturer: "Schneider", type: "RCD/RCCB", model: "Acti9 iID", rating: "25-100A", poles: "2P/4P", curve: "30-300mA, Type AC/A/B", about: "Acti9 residual current device available in Type A and Type B. Type B is required where variable speed drives can produce smooth DC residual current that would blind a Type AC device."),
      CatalogPart(id: "siemens-5sv", manufacturer: "Siemens", type: "RCD/RCCB", model: "SENTRON 5SV", rating: "25-125A", poles: "2P/4P", curve: "30-300mA", about: "SENTRON RCCB for group earth-leakage protection. Consider splitting circuits across several RCCBs so one nuisance trip does not take out an entire board.")
    ]),
    CatalogGroup(id: "mccbs", name: "MCCBs & ACBs", parts: [
      CatalogPart(id: "abb-tmax-xt1", manufacturer: "ABB", type: "MCCB", model: "SACE Tmax XT1", rating: "Set A - max 160A", poles: "3P/4P", curve: "Basic - thermal-magnetic", about: "Compact moulded case breaker for feeders up to 160A with a fixed thermal-magnetic trip. Suits outgoing ways on small distribution boards."),
      CatalogPart(id: "abb-tmax-xt2", manufacturer: "ABB", type: "MCCB", model: "SACE Tmax XT2", rating: "Set A - max 160A", poles: "3P/4P", curve: "Heavy duty - TM/Ekip Dip/Touch", about: "160A frame with a choice of thermal-magnetic or Ekip electronic trip units, giving adjustable settings for selectivity against downstream devices."),
      CatalogPart(id: "abb-tmax-xt3", manufacturer: "ABB", type: "MCCB", model: "SACE Tmax XT3", rating: "Set A - max 250A", poles: "3P/4P", curve: "Basic - thermal-magnetic", about: "250A frame thermal-magnetic breaker for mid-size feeders and sub-board supplies."),
      CatalogPart(id: "abb-tmax-xt4", manufacturer: "ABB", type: "MCCB", model: "SACE Tmax XT4", rating: "Set A - max 250A", poles: "3P/4P", curve: "Heavy duty - TM/Ekip Dip/Touch", about: "250A frame with electronic trip options, used where adjustable overload and instantaneous settings are needed to coordinate with upstream protection."),
      CatalogPart(id: "abb-tmax-xt5", manufacturer: "ABB", type: "MCCB", model: "SACE Tmax XT5", rating: "Set A - max 630A", poles: "3P/4P", curve: "Heavy duty - TM/Ekip Dip/Touch", about: "400 to 630A frame for major feeders, transformer outgoings and sub-main distribution."),
      CatalogPart(id: "abb-tmax-xt6", manufacturer: "ABB", type: "MCCB", model: "SACE Tmax XT6", rating: "Set A - max 1000A", poles: "3P/4P", curve: "Basic - thermal-magnetic/Ekip Dip", about: "630 to 800A frame typically used as a main incomer on medium boards or feeding large mechanical plant."),
      CatalogPart(id: "abb-tmax-xt7", manufacturer: "ABB", type: "MCCB", model: "SACE Tmax XT7", rating: "Set A - max 1600A", poles: "3P/4P", curve: "Heavy duty - Ekip Dip/Touch", about: "1000 to 1600A frame for main incoming protection on large distribution boards where an air circuit breaker is not required."),
      CatalogPart(id: "abb-tmax-xt7m", manufacturer: "ABB", type: "MCCB", model: "SACE Tmax XT7 M", rating: "Set A - max 1600A", poles: "3P/4P", curve: "Motorized - Ekip Dip/Touch", about: "Motorised version of the XT7 for remote or automatic operation, used in transfer schemes and where remote tripping is part of the control philosophy."),
      CatalogPart(id: "schneider-nsx", manufacturer: "Schneider", type: "MCCB", model: "Compact NSX", rating: "16-630A", poles: "3P/4P", curve: "TM/Micrologic", about: "Compact NSX moulded case breaker with interchangeable TM or Micrologic trip units. The electronic units add metering and adjustable protection curves."),
      CatalogPart(id: "schneider-nsj", manufacturer: "Schneider", type: "MCCB", model: "EasyPact CVS/NSX", rating: "16-630A", poles: "3P/4P", curve: "Thermal Magnetic", about: "Cost-focused moulded case breaker for standard distribution feeders where adjustable electronic protection is not required."),
      CatalogPart(id: "siemens-3va1", manufacturer: "Siemens", type: "MCCB", model: "SENTRON 3VA1", rating: "16-160A", poles: "3P/4P", curve: "Thermal Magnetic", about: "SENTRON moulded case breaker with thermal-magnetic trip for general distribution feeders."),
      CatalogPart(id: "siemens-3va2", manufacturer: "Siemens", type: "MCCB", model: "SENTRON 3VA2", rating: "25-630A", poles: "3P/4P", curve: "ETU", about: "SENTRON breaker with electronic trip units and optional communications, suited to boards where energy data and selectivity are both required."),
      CatalogPart(id: "eaton-nzm", manufacturer: "Eaton", type: "MCCB", model: "NZM", rating: "20-1600A", poles: "3P/4P", curve: "Electronic/TM", about: "Eaton moulded case breaker range covering a wide band of frame sizes, common as both incomer and outgoing protection in industrial boards."),
      CatalogPart(id: "eaton-bzmx", manufacturer: "Eaton", type: "MCCB", model: "BZMX", rating: "15-250A", poles: "3P/4P", curve: "Thermal Magnetic", about: "Compact moulded case breaker for smaller feeders where space in the board is limited."),
      CatalogPart(id: "generic-acb", manufacturer: "Generic", type: "ACB", model: "Air Circuit Breaker", rating: "Set A", poles: "3P/4P", curve: "Withdrawable/fixed", about: "Air circuit breaker for main incoming protection at high current, typically above 800A. Decide early whether it is fixed or withdrawable, since withdrawable versions need far more depth and a defined racking area in front of the board."),
      CatalogPart(id: "abb-emax2", manufacturer: "ABB", type: "ACB", model: "SACE Emax 2", rating: "630-6300A", poles: "3P/4P", curve: "Fixed or withdrawable", about: "Air circuit breaker for main incoming protection with Ekip trip units offering full protection, metering and communications. Withdrawable versions allow maintenance without a full shutdown but need defined racking space in front of the board."),
      CatalogPart(id: "schneider-mtz", manufacturer: "Schneider", type: "ACB", model: "MasterPact MTZ", rating: "630-6300A", poles: "3P/4P", curve: "Micrologic X", about: "Main air circuit breaker with Micrologic X control units providing measurement, diagnostics and remote connectivity. Common as the incomer on large main LV boards."),
      CatalogPart(id: "siemens-3wa", manufacturer: "Siemens", type: "ACB", model: "SENTRON 3WA", rating: "630-6300A", poles: "3P/4P", curve: "ETU trip unit", about: "SENTRON air circuit breaker for main and coupler positions. Confirm the trip unit family early since it drives the metering and communications you can offer later."),
      CatalogPart(id: "eaton-izmx", manufacturer: "Eaton", type: "ACB", model: "IZMX", rating: "630-1600A", poles: "3P/4P", curve: "Fixed or withdrawable", about: "Compact air circuit breaker for main protection where panel depth is constrained but ACB features are still required.")
    ]),
    CatalogGroup(id: "surge-arc", name: "Surge & Arc Protection", parts: [
      CatalogPart(id: "generic-spd", manufacturer: "Generic", type: "SPD", model: "Surge Protection Device", rating: "Type 2", poles: "3P+N", curve: "40kA", about: "Surge protection device diverting transient overvoltage from lightning and switching to earth. Type 1 goes at the origin where there is a lightning protection system, Type 2 at distribution boards. It needs a correctly rated backup fuse or breaker and the shortest possible connecting leads."),
      CatalogPart(id: "abb-ovr", manufacturer: "ABB", type: "SPD", model: "OVR T2", rating: "Type 2", poles: "1P-4P", curve: "40kA Imax", about: "Type 2 surge arrester for distribution boards, diverting switching and induced lightning transients. Keep the connecting leads under half a metre or the let-through voltage rises sharply."),
      CatalogPart(id: "schneider-iprd", manufacturer: "Schneider", type: "SPD", model: "Acti9 iPRD", rating: "Type 2", poles: "1P-4P", curve: "20-65kA", about: "Acti9 surge protection with a status window showing when the cartridge is spent, and a remote signalling contact so a failed arrester does not sit unnoticed."),
      CatalogPart(id: "phoenix-valms", manufacturer: "Phoenix", type: "SPD", model: "VAL-MS", rating: "Type 2", poles: "1P-4P", curve: "Pluggable", about: "Pluggable surge protection where the protection module can be replaced without disturbing the wiring, useful on boards in high-exposure locations."),
      CatalogPart(id: "abb-afdd", manufacturer: "ABB", type: "AFDD", model: "S-ARC1", rating: "6-40A", poles: "1P+N", curve: "B/C Curve", about: "Arc fault detection device recognising the signature of a series or parallel arcing fault that a normal MCB or RCD will not see. Specified for fire risk areas such as sleeping accommodation and timber structures."),
      CatalogPart(id: "siemens-5sm6", manufacturer: "Siemens", type: "AFDD", model: "5SM6", rating: "6-40A", poles: "1P+N", curve: "Combined MCB", about: "Arc fault detection combined with overcurrent protection in one device, reducing the DIN width needed compared with separate units."),
      CatalogPart(id: "abb-cm-iwx", manufacturer: "ABB", type: "RCM", model: "CM-IWx", rating: "30mA-30A", poles: "DIN", curve: "Residual current monitor", about: "Residual current monitor that measures and reports leakage continuously instead of tripping, letting you catch a deteriorating circuit before it causes an outage.")
    ]),
    CatalogGroup(id: "switching", name: "Switching & Isolation", parts: [
      CatalogPart(id: "generic-isolator", manufacturer: "Generic", type: "Isolator", model: "Load break switch", rating: "Set A", poles: "3P/4P", curve: "Door-coupled", about: "Load break switch providing a visible, lockable point of isolation so a board or section can be worked on safely. Rated for making and breaking load current, unlike a plain disconnector."),
      CatalogPart(id: "abb-ot", manufacturer: "ABB", type: "Isolator", model: "OT switch disconnector", rating: "16-3150A", poles: "3P/4P", curve: "Door or base mount", about: "Switch disconnector for main isolation or outgoing feeders, available with door-coupled rotary handles that can be padlocked off for safe working."),
      CatalogPart(id: "schneider-ins", manufacturer: "Schneider", type: "Isolator", model: "Interpact INS", rating: "40-2500A", poles: "3P/4P", curve: "Load break", about: "Load break switch for isolation duty on incomers and outgoing feeders where switching capability without protection is required."),
      CatalogPart(id: "generic-changeover", manufacturer: "Generic", type: "Changeover Switch", model: "Manual changeover", rating: "Set A", poles: "4P", curve: "I-0-II", about: "Manual changeover switch selecting between two supplies, typically utility and generator. The I-0-II arrangement mechanically prevents both sources being connected at once."),
      CatalogPart(id: "socomec-sirco", manufacturer: "Socomec", type: "Changeover Switch", model: "Sirco MOT", rating: "125-3200A", poles: "3P/4P", curve: "Motorised I-0-II", about: "Motorised changeover switch for automatic transfer between utility and generator, mechanically interlocked so both sources can never be paralleled."),
      CatalogPart(id: "abb-ats021", manufacturer: "ABB", type: "ATS Controller", model: "ATS021", rating: "24VDC", poles: "DIN", curve: "Auto transfer control", about: "Automatic transfer controller monitoring the normal supply and commanding changeover to the standby source. Set the transfer and return delays deliberately so brief dips do not start the generator unnecessarily."),
      CatalogPart(id: "deepsea-dse", manufacturer: "Generic", type: "ATS Controller", model: "Generator controller", rating: "12/24VDC", poles: "Door mount", curve: "Auto mains failure", about: "Auto mains failure controller starting the generator on supply loss, transferring load and returning it once the mains is stable. It needs clear wiring to the generator start contacts and both source sensing points."),
      CatalogPart(id: "generic-fuse", manufacturer: "Generic", type: "Fuse", model: "NH fuse link", rating: "Set A", poles: "1P", curve: "gG/gL", about: "NH fuse link giving very high breaking capacity in a compact body, often used ahead of large feeders or where the fault level exceeds what a breaker can handle economically. gG is for general cable protection, aM for motor circuits."),
      CatalogPart(id: "generic-fuse-holder", manufacturer: "Generic", type: "Fuse Holder", model: "DIN fuse holder", rating: "Set A", poles: "1P/3P", curve: "10x38/NH", about: "DIN rail fuse carrier holding cartridge or NH fuse links, giving isolation when the carrier is withdrawn. Confirm the fuse size it accepts and whether a blown-fuse indicator is required."),
      CatalogPart(id: "abb-af16-30-10", manufacturer: "ABB", type: "Contactor", model: "AF16-30-10", rating: "16A", poles: "3P", curve: "1NO Aux", about: "Three-pole contactor around 16A AC-3 with one normally-open auxiliary, sized for small motors and controlled loads. The AF electronic coil accepts a wide voltage band, which reduces the number of coil variants to stock."),
      CatalogPart(id: "abb-af26-30-00", manufacturer: "ABB", type: "Contactor", model: "AF26-30-00", rating: "26A", poles: "3P", curve: "No Aux", about: "Mid-size three-pole contactor for motor and load switching where no built-in auxiliary contact is required."),
      CatalogPart(id: "abb-af38-30-00", manufacturer: "ABB", type: "Contactor", model: "AF38-30-00", rating: "38A", poles: "3P", curve: "No Aux", about: "Larger three-pole contactor for motors up to roughly 18.5kW at 400V. Check AC-3 rating against motor full-load amps rather than the AC-1 figure."),
      CatalogPart(id: "schneider-lc1d", manufacturer: "Schneider", type: "Contactor", model: "TeSys D", rating: "9-150A", poles: "3P", curve: "AC-3", about: "TeSys D contactor, the workhorse for motor starters and load switching. Add-on auxiliary blocks and mechanical interlocks let it build reversing and star-delta arrangements."),
      CatalogPart(id: "siemens-3rt", manufacturer: "Siemens", type: "Contactor", model: "SIRIUS 3RT", rating: "9-250A", poles: "3P", curve: "AC-3", about: "SIRIUS contactor sized by frame across a wide kW range, designed to clip together with matching 3RU or 3RB overload relays into a compact starter."),
      CatalogPart(id: "eaton-dilm", manufacturer: "Eaton", type: "Contactor", model: "DILM", rating: "7-170A", poles: "3P", curve: "AC-3", about: "Eaton DILM contactor range with matching overloads and accessory blocks, common in machine control panels.")
    ]),
    CatalogGroup(id: "drives", name: "Drives & Soft Starters", parts: [
      CatalogPart(id: "abb-acs355", manufacturer: "ABB", type: "VFD", model: "ACS355", rating: "0.37-22kW", poles: "3PH", curve: "Machinery drive", about: "Machinery drive for conveyors, mixers and small pumps, built for panel mounting with straightforward parameter setup."),
      CatalogPart(id: "abb-acs580", manufacturer: "ABB", type: "VFD", model: "ACS580", rating: "0.75-250kW", poles: "3PH", curve: "General purpose", about: "General purpose drive covering most building services and industrial motor loads, with a built-in choke that reduces harmonic current without an external reactor."),
      CatalogPart(id: "abb-ach580", manufacturer: "ABB", type: "VFD", model: "ACH580", rating: "0.75-500kW", poles: "3PH", curve: "HVAC drive", about: "HVAC variant tuned for fans and pumps, including firefighter override and PID control for pressure and flow."),
      CatalogPart(id: "abb-acs880", manufacturer: "ABB", type: "VFD", model: "ACS880", rating: "0.55-3200kW", poles: "3PH", curve: "Industrial drive", about: "Industrial drive for demanding applications including regenerative and common DC bus configurations. Confirm cooling and cabinet depth early, since larger frames are substantial."),
      CatalogPart(id: "schneider-atv12", manufacturer: "Schneider", type: "VFD", model: "Altivar ATV12", rating: "0.18-4kW", poles: "1PH/3PH", curve: "Basic machines", about: "Entry-level drive for small machines and single-phase supplies, typically fitted straight onto the machine panel."),
      CatalogPart(id: "schneider-atv320", manufacturer: "Schneider", type: "VFD", model: "Altivar ATV320", rating: "0.18-15kW", poles: "3PH", curve: "Machine drive", about: "Compact machine drive available in book and compact formats, with integrated safety functions such as Safe Torque Off."),
      CatalogPart(id: "schneider-atv340", manufacturer: "Schneider", type: "VFD", model: "Altivar ATV340", rating: "0.75-75kW", poles: "3PH", curve: "High performance", about: "High performance drive for dynamic machine control where fast response and precise speed regulation matter."),
      CatalogPart(id: "schneider-atv630", manufacturer: "Schneider", type: "VFD", model: "Altivar ATV630", rating: "0.75-315kW", poles: "3PH", curve: "Process drive", about: "Process drive for pumps, fans and compressors with energy-saving control and built-in EMC filtering."),
      CatalogPart(id: "siemens-v20", manufacturer: "Siemens", type: "VFD", model: "SINAMICS V20", rating: "0.12-30kW", poles: "1PH/3PH", curve: "Basic drive", about: "Basic drive for simple fan, pump and conveyor duties where a full parameter set would be overkill."),
      CatalogPart(id: "siemens-g120c", manufacturer: "Siemens", type: "VFD", model: "SINAMICS G120C", rating: "0.55-132kW", poles: "3PH", curve: "Compact drive", about: "Compact single-unit drive combining control and power in one housing, saving panel width against the modular G120."),
      CatalogPart(id: "siemens-g120", manufacturer: "Siemens", type: "VFD", model: "SINAMICS G120", rating: "0.55-250kW", poles: "3PH", curve: "Modular drive", about: "Modular drive where control unit and power module are selected separately, so the same power module can serve different control and communication needs."),
      CatalogPart(id: "danfoss-fc51", manufacturer: "Danfoss", type: "VFD", model: "VLT Micro FC 51", rating: "0.18-22kW", poles: "1PH/3PH", curve: "Micro drive", about: "Micro drive for basic speed control on small motors, common in HVAC and simple machinery."),
      CatalogPart(id: "danfoss-fc202", manufacturer: "Danfoss", type: "VFD", model: "VLT AQUA FC 202", rating: "0.25-1400kW", poles: "3PH", curve: "Pump drive", about: "Drive tuned for water and wastewater duty, with pump-specific features such as dry-run detection, pipe fill and cascade control."),
      CatalogPart(id: "danfoss-fc302", manufacturer: "Danfoss", type: "VFD", model: "VLT Automation FC 302", rating: "0.25-800kW", poles: "3PH", curve: "Automation drive", about: "Automation drive for demanding motor control including closed loop and servo-like applications."),
      CatalogPart(id: "delta-ms300", manufacturer: "Delta", type: "VFD", model: "MS300", rating: "0.4-22kW", poles: "3PH", curve: "Compact vector", about: "Compact vector drive giving good torque control in a small footprint, widely used in OEM machine panels."),
      CatalogPart(id: "delta-c2000", manufacturer: "Delta", type: "VFD", model: "C2000+", rating: "0.75-400kW", poles: "3PH", curve: "Heavy duty vector", about: "Heavy duty vector drive for cranes, hoists and high-torque applications where overload capability matters."),
      CatalogPart(id: "eaton-dc1", manufacturer: "Eaton", type: "VFD", model: "PowerXL DC1", rating: "0.37-11kW", poles: "1PH/3PH", curve: "Compact drive", about: "Compact drive for basic speed control, sized for small panels and simple commissioning."),
      CatalogPart(id: "eaton-dg1", manufacturer: "Eaton", type: "VFD", model: "PowerXL DG1", rating: "0.75-250kW", poles: "3PH", curve: "General purpose", about: "General purpose drive with active energy control, used across pump, fan and conveyor duties."),
      CatalogPart(id: "generic-soft-starter", manufacturer: "Generic", type: "Soft Starter", model: "Motor soft starter", rating: "Set kW", poles: "3PH", curve: "Ramp start/stop", about: "Ramps motor voltage up and down to limit inrush current and mechanical shock on belts, couplings and pumps. Confirm whether a bypass is built in, and remember it still needs upstream isolation and overload protection."),
      CatalogPart(id: "abb-psr", manufacturer: "ABB", type: "Soft Starter", model: "PSR", rating: "3-105A", poles: "3PH", curve: "Compact ramp", about: "Compact soft starter for small motors where the aim is simply to take the shock out of starting. No internal bypass, so allow for the heat it dissipates while ramping."),
      CatalogPart(id: "abb-pse", manufacturer: "ABB", type: "Soft Starter", model: "PSE", rating: "18-370A", poles: "3PH", curve: "Bypass + current limit", about: "Soft starter with internal bypass and current limiting, so it stops dissipating heat once the motor is up to speed."),
      CatalogPart(id: "abb-pstx", manufacturer: "ABB", type: "Soft Starter", model: "PSTX", rating: "30-1250A", poles: "3PH", curve: "Advanced, built-in bypass", about: "Advanced soft starter with built-in bypass, torque control and motor protection, suitable for large pumps and compressors where starting stress is a real problem."),
      CatalogPart(id: "schneider-ats01", manufacturer: "Schneider", type: "Soft Starter", model: "Altistart ATS01", rating: "3-32A", poles: "3PH", curve: "Basic ramp", about: "Basic soft starter for small motors, providing a simple voltage ramp without configurable protection."),
      CatalogPart(id: "schneider-ats22", manufacturer: "Schneider", type: "Soft Starter", model: "Altistart ATS22", rating: "17-590A", poles: "3PH", curve: "Torque control", about: "Soft starter with torque control giving smoother starts and stops on pumps, which reduces water hammer in pipework."),
      CatalogPart(id: "schneider-ats480", manufacturer: "Schneider", type: "Soft Starter", model: "Altistart ATS480", rating: "17-1200A", poles: "3PH", curve: "Advanced, bypass", about: "Advanced soft starter with integrated bypass, protection and diagnostics for larger motors and critical duties."),
      CatalogPart(id: "siemens-3rw30", manufacturer: "Siemens", type: "Soft Starter", model: "SIRIUS 3RW30", rating: "3-106A", poles: "3PH", curve: "Standard ramp", about: "Standard soft starter for straightforward ramp starting on general purpose motors."),
      CatalogPart(id: "siemens-3rw52", manufacturer: "Siemens", type: "Soft Starter", model: "SIRIUS 3RW52", rating: "13-370A", poles: "3PH", curve: "Bypass + protection", about: "Soft starter combining bypass and motor protection in one device, reducing the component count in the starter section."),
      CatalogPart(id: "siemens-3rw44", manufacturer: "Siemens", type: "Soft Starter", model: "SIRIUS 3RW44", rating: "29-1214A", poles: "3PH", curve: "High feature", about: "High-feature soft starter for large motors with adjustable torque control and comprehensive protection and diagnostics."),
      CatalogPart(id: "eaton-ds7", manufacturer: "Eaton", type: "Soft Starter", model: "DS7", rating: "9-135A", poles: "3PH", curve: "Integrated bypass", about: "Soft starter with integrated bypass controlling two phases, compact enough to fit where a full three-phase controlled unit would not.")
    ]),
    CatalogGroup(id: "motor-protection", name: "Motor Protection & Starters", parts: [
      CatalogPart(id: "abb-ms132", manufacturer: "ABB", type: "MPCB", model: "MS132", rating: "0.1-32A", poles: "3P", curve: "Manual motor starter", about: "Manual motor starter combining short-circuit, overload and manual switching in one device. Dial the current setting to motor full-load amps and check the breaking capacity against the board fault level."),
      CatalogPart(id: "abb-ms165", manufacturer: "ABB", type: "MPCB", model: "MS165", rating: "10-65A", poles: "3P", curve: "Manual motor starter", about: "Larger frame manual motor starter for motors up to roughly 30kW, with the same combined protection and switching function."),
      CatalogPart(id: "schneider-gv2me", manufacturer: "Schneider", type: "MPCB", model: "TeSys GV2ME", rating: "0.1-32A", poles: "3P", curve: "Thermal-magnetic", about: "TeSys manual motor starter with thermal-magnetic protection and a rotary handle, commonly the first device in a compact motor feeder."),
      CatalogPart(id: "schneider-gv3", manufacturer: "Schneider", type: "MPCB", model: "TeSys GV3", rating: "9-65A", poles: "3P", curve: "Thermal-magnetic", about: "Larger TeSys motor circuit breaker for mid-size motors, often paired with a matching contactor to form a compact starter."),
      CatalogPart(id: "siemens-3rv2", manufacturer: "Siemens", type: "MPCB", model: "SIRIUS 3RV2", rating: "0.11-100A", poles: "3P", curve: "Motor protection", about: "SIRIUS motor starter protector that clips directly to matching 3RT contactors, forming a tested combination without extra wiring."),
      CatalogPart(id: "eaton-pkzm0", manufacturer: "Eaton", type: "MPCB", model: "PKZM0", rating: "0.1-32A", poles: "3P", curve: "Motor protective", about: "Motor protective circuit breaker with adjustable overload, used as a compact combined isolator and protection device."),
      CatalogPart(id: "generic-overload", manufacturer: "Generic", type: "Overload Relay", model: "Thermal overload relay", rating: "Set A", poles: "3P", curve: "Motor protection", about: "Thermal overload relay protecting a motor from sustained overcurrent such as a jammed load or lost phase. Set the dial to motor full-load amps and check the trip class suits the starting time."),
      CatalogPart(id: "abb-ta25du", manufacturer: "ABB", type: "Overload Relay", model: "TA25DU", rating: "0.1-32A", poles: "3P", curve: "Thermal, Class 10", about: "Thermal overload relay mounting directly onto matching contactors. Set the dial to motor full-load amps, and reset behaviour should be chosen deliberately since automatic reset on a motor can restart machinery."),
      CatalogPart(id: "abb-ef19", manufacturer: "ABB", type: "Overload Relay", model: "EF19", rating: "0.1-18.9A", poles: "3P", curve: "Electronic, Class 10-30", about: "Electronic overload relay with a wider setting range and selectable trip class, holding accuracy better than a bimetallic relay across ambient changes."),
      CatalogPart(id: "schneider-lrd", manufacturer: "Schneider", type: "Overload Relay", model: "TeSys LRD", rating: "0.1-140A", poles: "3P", curve: "Thermal, Class 10/20", about: "TeSys thermal overload relay clipping onto LC1D contactors, the standard partner in a Schneider motor starter."),
      CatalogPart(id: "schneider-lr9", manufacturer: "Schneider", type: "Overload Relay", model: "TeSys LR9", rating: "0.3-630A", poles: "3P", curve: "Electronic", about: "Electronic overload relay for larger motors, with a wide adjustment range and better protection against phase loss."),
      CatalogPart(id: "siemens-3ru21", manufacturer: "Siemens", type: "Overload Relay", model: "SIRIUS 3RU21", rating: "0.11-100A", poles: "3P", curve: "Thermal, Class 10", about: "Thermal overload relay designed to mount directly on 3RT contactors, forming a compact tested starter combination."),
      CatalogPart(id: "siemens-3rb30", manufacturer: "Siemens", type: "Overload Relay", model: "SIRIUS 3RB30", rating: "0.1-100A", poles: "3P", curve: "Electronic, Class 5-30", about: "Electronic overload relay with selectable trip class from 5 to 30, useful for motors with long run-up times such as large fans."),
      CatalogPart(id: "generic-dol-starter", manufacturer: "Generic", type: "Motor Starter", model: "Direct-on-line starter", rating: "Set kW", poles: "3PH", curve: "Contactor + overload", about: "Direct-on-line starter combining contactor and overload for the simplest motor start. Draws six to eight times full-load current at start, so confirm the supply and any generator can accept that step."),
      CatalogPart(id: "generic-star-delta", manufacturer: "Generic", type: "Motor Starter", model: "Star-delta starter", rating: "Set kW", poles: "3PH", curve: "3 contactors + timer", about: "Star-delta starter reducing starting current by first running the motor in star, then switching to delta. The motor must have all six leads available and the transition timer needs setting to the actual run-up time."),
      CatalogPart(id: "generic-reversing", manufacturer: "Generic", type: "Motor Starter", model: "Reversing starter", rating: "Set kW", poles: "3PH", curve: "Interlocked pair", about: "Reversing starter using two mechanically and electrically interlocked contactors to swap two phases. The interlock is a safety requirement, not an option, since both closing together is a direct phase-to-phase fault.")
    ]),
    CatalogGroup(id: "control-power", name: "Control Power & UPS", parts: [
      CatalogPart(id: "generic-transformer", manufacturer: "Generic", type: "Transformer", model: "Control transformer", rating: "Set VA", poles: "1PH", curve: "400/230V", about: "Control transformer stepping the panel supply down to a separate control voltage, typically 230V or 110V, and isolating the control circuit from the power circuit. Size the VA for the inrush of all contactor coils picking up together, not just their holding current."),
      CatalogPart(id: "phoenix-step", manufacturer: "Phoenix", type: "PSU", model: "STEP POWER", rating: "24VDC", poles: "1PH", curve: "0.5-10A basic", about: "Basic 24VDC supply for small control loads such as a handful of relays and sensors, where power reserve features are unnecessary."),
      CatalogPart(id: "phoenix-trio", manufacturer: "Phoenix", type: "PSU", model: "TRIO POWER", rating: "24VDC", poles: "1PH/3PH", curve: "2.5-20A", about: "Mid-range 24VDC supply for typical control panels, with a stable output and compact DIN footprint."),
      CatalogPart(id: "phoenix-quint", manufacturer: "Phoenix", type: "PSU", model: "QUINT POWER", rating: "24VDC", poles: "1PH/3PH", curve: "5-40A, SFB tech", about: "Premium 24VDC supply whose selective fuse breaking technology delivers extra current briefly, so a downstream fault clears its protective device instead of dragging the whole 24V rail down."),
      CatalogPart(id: "abb-cpd", manufacturer: "ABB", type: "PSU", model: "CP-D", rating: "24VDC", poles: "1PH", curve: "0.42-2.5A compact", about: "Compact 24VDC supply for small control tasks where DIN width is at a premium."),
      CatalogPart(id: "abb-cpe", manufacturer: "ABB", type: "PSU", model: "CP-E", rating: "24VDC", poles: "1PH", curve: "0.75-20A", about: "General purpose 24VDC supply covering most panel control loads, with adjustable output voltage to compensate for line drop."),
      CatalogPart(id: "siemens-psu100s", manufacturer: "Siemens", type: "PSU", model: "SITOP PSU100S", rating: "24VDC", poles: "1PH", curve: "2.5-40A", about: "Single-phase SITOP supply for control circuits and SIMATIC controllers, with reserve capacity for short overloads."),
      CatalogPart(id: "siemens-psu8200", manufacturer: "Siemens", type: "PSU", model: "SITOP PSU8200", rating: "24VDC", poles: "3PH", curve: "10-40A", about: "Three-phase SITOP supply for larger 24VDC loads, balancing the draw across all three phases rather than loading one."),
      CatalogPart(id: "meanwell-dr", manufacturer: "Mean Well", type: "PSU", model: "DR series", rating: "24VDC", poles: "1PH", curve: "15-120W", about: "Economical DIN rail supply for light control duties, widely used in OEM panels."),
      CatalogPart(id: "meanwell-hdr", manufacturer: "Mean Well", type: "PSU", model: "HDR series", rating: "24VDC", poles: "1PH", curve: "15-150W ultra slim", about: "Ultra-slim DIN supply for tight enclosures where every millimetre of rail counts."),
      CatalogPart(id: "meanwell-ndr", manufacturer: "Mean Well", type: "PSU", model: "NDR series", rating: "24VDC", poles: "1PH", curve: "75-480W", about: "Higher power DIN supply for panels with substantial 24VDC load such as banks of valves or extensive I/O."),
      CatalogPart(id: "meanwell-tdr", manufacturer: "Mean Well", type: "PSU", model: "TDR series", rating: "24VDC", poles: "3PH", curve: "240-960W", about: "Three-phase DIN supply for heavy 24VDC loads, keeping phase loading balanced on larger installations."),
      CatalogPart(id: "delta-drp", manufacturer: "Delta", type: "PSU", model: "CliQ DRP", rating: "24VDC", poles: "1PH/3PH", curve: "60-960W", about: "CliQ series supply available in single and three-phase versions with good efficiency and a compact footprint."),
      CatalogPart(id: "eaton-psg", manufacturer: "Eaton", type: "PSU", model: "PSG", rating: "24VDC", poles: "1PH", curve: "1.3-20A", about: "General purpose 24VDC supply for control circuits, with models sized from small interface duty upward."),
      CatalogPart(id: "phoenix-quint-ups", manufacturer: "Phoenix", type: "DC-UPS", model: "QUINT UPS-IQ", rating: "24VDC", poles: "DIN", curve: "5-40A + battery", about: "DC uninterruptible supply with intelligent battery management that reports remaining backup time, so control power outlives a brief mains loss."),
      CatalogPart(id: "siemens-ups1600", manufacturer: "Siemens", type: "DC-UPS", model: "SITOP UPS1600", rating: "24VDC", poles: "DIN", curve: "10-40A managed", about: "Managed DC-UPS with configurable buffer time and diagnostics over the controller network, letting a PLC shut down cleanly rather than dying mid-operation."),
      CatalogPart(id: "abb-cpa-ru", manufacturer: "ABB", type: "DC-UPS", model: "CP-A RU", rating: "24VDC", poles: "DIN", curve: "Redundancy + buffer", about: "Redundancy and buffer module decoupling two power supplies so a single failed unit cannot pull down the shared 24V rail."),
      CatalogPart(id: "meanwell-drc", manufacturer: "Mean Well", type: "DC-UPS", model: "DRC series", rating: "24VDC", poles: "DIN", curve: "Charger + backup", about: "DIN rail supply with an integrated battery charger and changeover, a cost-effective route to backed-up control power on smaller panels.")
    ]),
    CatalogGroup(id: "control-automation", name: "Control & Automation", parts: [
      CatalogPart(id: "generic-plc", manufacturer: "Generic", type: "PLC", model: "Compact PLC", rating: "24VDC", poles: "DIN", curve: "Digital I/O", about: "Programmable logic controller running the panel control sequence. Count the digital and analogue I/O needed with spare capacity, and confirm the communication protocol before fixing the enclosure layout."),
      CatalogPart(id: "siemens-s71200", manufacturer: "Siemens", type: "PLC", model: "SIMATIC S7-1200", rating: "24VDC", poles: "DIN", curve: "Compact controller", about: "Compact controller for panel automation with expandable digital and analogue I/O. Confirm the I/O count with spare capacity and whether PROFINET or Modbus is required before finalising the layout."),
      CatalogPart(id: "schneider-m221", manufacturer: "Schneider", type: "PLC", model: "Modicon M221", rating: "24VDC", poles: "DIN", curve: "Machine controller", about: "Machine controller for pump, HVAC and small process panels, with built-in Ethernet on most references."),
      CatalogPart(id: "abb-ac500", manufacturer: "ABB", type: "PLC", model: "AC500-eCo", rating: "24VDC", poles: "DIN", curve: "Modular controller", about: "Modular controller that scales from small to large I/O counts, useful where the same panel design must cover several plant sizes."),
      CatalogPart(id: "delta-dvp", manufacturer: "Delta", type: "PLC", model: "DVP series", rating: "24VDC", poles: "DIN", curve: "Compact controller", about: "Cost-effective compact PLC widely used in OEM machine panels with straightforward digital and analogue expansion."),
      CatalogPart(id: "siemens-ktp", manufacturer: "Siemens", type: "HMI", model: "SIMATIC KTP", rating: "24VDC", poles: "Door mount", curve: "4-15 inch touch", about: "Door-mounted touch panel giving the operator status, alarms and setpoints. Cutting the door aperture accurately matters, and the IP rating only holds if the supplied gasket is fitted correctly."),
      CatalogPart(id: "schneider-hmigxu", manufacturer: "Schneider", type: "HMI", model: "Harmony HMIGXU", rating: "24VDC", poles: "Door mount", curve: "3.5-7 inch touch", about: "Compact operator terminal for smaller panels where a full PC-based interface is unnecessary."),
      CatalogPart(id: "pilz-pnoz", manufacturer: "Generic", type: "Safety Relay", model: "PNOZ safety relay", rating: "24VDC", poles: "DIN", curve: "Emergency stop / guard", about: "Safety relay monitoring emergency stops, guard switches and light curtains, providing a redundant and monitored trip path. It must be wired to the documented category and cannot be bypassed by ordinary control logic."),
      CatalogPart(id: "siemens-3sk1", manufacturer: "Siemens", type: "Safety Relay", model: "SIRIUS 3SK1", rating: "24VDC", poles: "DIN", curve: "Safety monitoring", about: "Safety relay for emergency stop and guard monitoring with expandable output modules for larger safety circuits."),
      CatalogPart(id: "generic-relay", manufacturer: "Generic", type: "Relay", model: "Interface relay", rating: "24VDC", poles: "DIN", curve: "1CO/2CO", about: "Interface relay isolating low-power controller outputs from the coils and loads they switch, and converting between control voltages. The slim DIN format keeps a dense I/O interface tidy."),
      CatalogPart(id: "phoenix-plcrsc", manufacturer: "Phoenix", type: "Relay", model: "PLC-RSC interface", rating: "24VDC", poles: "DIN", curve: "6.2mm slim", about: "Slim plug-in interface relay isolating controller outputs from field loads. The pluggable design lets a failed relay be swapped without disturbing terminal wiring."),
      CatalogPart(id: "finder-55", manufacturer: "Generic", type: "Relay", model: "Finder 55 series", rating: "24-230V", poles: "DIN", curve: "2CO/3CO", about: "General purpose plug-in relay with a socket base, used for interposing and simple control logic in panels of every size."),
      CatalogPart(id: "generic-timer", manufacturer: "Generic", type: "Timer", model: "Time relay", rating: "24-230V", poles: "DIN", curve: "On/off delay", about: "Time relay providing on-delay, off-delay or cyclic switching for sequencing, pump alternation and star-delta transitions."),
      CatalogPart(id: "finder-80", manufacturer: "Generic", type: "Timer", model: "Finder 80 multifunction", rating: "12-240V", poles: "DIN", curve: "Multifunction", about: "Multifunction timer covering on-delay, off-delay, interval and cyclic modes in one part, which cuts down on stocked variants."),
      CatalogPart(id: "abb-cm-mps", manufacturer: "ABB", type: "Monitoring Relay", model: "CM-MPS", rating: "3x400V", poles: "DIN", curve: "Phase failure / sequence", about: "Three-phase monitoring relay detecting phase loss, wrong phase sequence, under and overvoltage. It is what stops a motor running single-phased after an upstream fuse clears one leg."),
      CatalogPart(id: "siemens-3ug4", manufacturer: "Siemens", type: "Monitoring Relay", model: "SIRIUS 3UG4", rating: "3x400V", poles: "DIN", curve: "Voltage / phase monitor", about: "Line monitoring relay for phase sequence, asymmetry and voltage window, commonly interlocked into the start circuit of motor panels.")
    ]),
    CatalogGroup(id: "metering", name: "Metering & Monitoring", parts: [
      CatalogPart(id: "generic-meter", manufacturer: "Generic", type: "Meter", model: "Digital meter", rating: "230/400V", poles: "3PH", curve: "Panel mount", about: "Panel-mounted digital meter showing voltage, current and basic energy values on the board door. Confirm whether it measures directly or needs current transformers."),
      CatalogPart(id: "schneider-iem3000", manufacturer: "Schneider", type: "Meter", model: "Acti9 iEM3000", rating: "230/400V", poles: "3PH", curve: "DIN, Modbus", about: "DIN rail energy meter for sub-billing and consumption monitoring, available in direct-connect and CT versions with Modbus output."),
      CatalogPart(id: "siemens-pac3200", manufacturer: "Siemens", type: "Meter", model: "SENTRON PAC3200", rating: "230/400V", poles: "3PH", curve: "Door mount", about: "Door-mounted multifunction meter showing the full set of electrical values with Modbus or PROFINET reporting."),
      CatalogPart(id: "carlogavazzi-em21", manufacturer: "Generic", type: "Meter", model: "Carlo Gavazzi EM21", rating: "230/400V", poles: "3PH", curve: "DIN, Modbus", about: "Compact DIN rail energy meter widely used for sub-metering individual feeders in tenant and process installations."),
      CatalogPart(id: "generic-power-analyzer", manufacturer: "Generic", type: "Power Analyzer", model: "Power quality analyzer", rating: "230/400V", poles: "3PH", curve: "Modbus", about: "Power quality analyser recording harmonics, power factor, demand and event data, usually reporting over Modbus to a monitoring system. Specify where energy billing or harmonic problems need evidence."),
      CatalogPart(id: "schneider-pm2000", manufacturer: "Schneider", type: "Power Analyzer", model: "PowerLogic PM2000", rating: "230/400V", poles: "3PH", curve: "Panel mount", about: "Panel-mounted power meter measuring energy, demand and basic power quality, suited to tenant metering and energy management."),
      CatalogPart(id: "siemens-pac4200", manufacturer: "Siemens", type: "Power Analyzer", model: "SENTRON PAC4200", rating: "230/400V", poles: "3PH", curve: "Harmonics + logging", about: "Advanced meter adding harmonic analysis and data logging, used where power quality has to be proven rather than assumed."),
      CatalogPart(id: "abb-m2m", manufacturer: "ABB", type: "Power Analyzer", model: "M2M network analyzer", rating: "230/400V", poles: "3PH", curve: "Modbus", about: "Network analyser recording power quality and harmonic content, typically fitted where drives and non-linear loads dominate."),
      CatalogPart(id: "generic-ct", manufacturer: "Generic", type: "Current Transformer", model: "Split or solid core CT", rating: "50-5000A", poles: "1PH each", curve: "Class 0.5-1", about: "Current transformer scaling feeder current down to a meter input, usually 5A or 1A. Match the ratio and accuracy class to the meter, and never leave the secondary open circuit while primary current flows."),
      CatalogPart(id: "generic-test-block", manufacturer: "Generic", type: "Test Block", model: "CT test block", rating: "5A", poles: "Panel mount", curve: "Shorting type", about: "Test block allowing meters and protection relays to be tested or replaced without breaking the CT secondary, which it shorts automatically as the plug is withdrawn.")
    ]),
    CatalogGroup(id: "power-quality", name: "Power Factor & Quality", parts: [
      CatalogPart(id: "abb-rvt", manufacturer: "ABB", type: "PFC Controller", model: "RVT controller", rating: "230/400V", poles: "Door mount", curve: "6-12 stages", about: "Power factor controller switching capacitor stages to hold the target power factor and avoid reactive energy charges. Set the target and the C/k ratio to suit the CT and the smallest stage."),
      CatalogPart(id: "schneider-varlogic", manufacturer: "Schneider", type: "PFC Controller", model: "Varlogic NR", rating: "230/400V", poles: "Door mount", curve: "6-12 stages", about: "Power factor controller with stage health monitoring, which matters because a failed capacitor stage otherwise goes unnoticed until the bill rises."),
      CatalogPart(id: "abb-clmd", manufacturer: "ABB", type: "Capacitor", model: "CLMD capacitor", rating: "Set kVAr", poles: "3PH", curve: "Dry type", about: "Dry-type power capacitor forming the stages of a correction bank. Capacitors need discharge resistors and adequate ventilation, and they age faster in hot or harmonic-rich environments."),
      CatalogPart(id: "generic-detuned-reactor", manufacturer: "Generic", type: "Reactor", model: "Detuned reactor", rating: "Set kVAr", poles: "3PH", curve: "7% or 14%", about: "Detuned reactor placed in series with capacitor stages to shift the resonant frequency away from prevailing harmonics. Required wherever significant drive or UPS load shares the installation."),
      CatalogPart(id: "generic-line-reactor", manufacturer: "Generic", type: "Reactor", model: "Line/load reactor", rating: "Set A", poles: "3PH", curve: "2-5% impedance", about: "Line or load reactor fitted with a drive to reduce current distortion, protect the drive input and limit voltage stress on long motor cables."),
      CatalogPart(id: "generic-active-filter", manufacturer: "Generic", type: "Harmonic Filter", model: "Active harmonic filter", rating: "30-300A", poles: "3PH", curve: "Real time correction", about: "Active filter injecting counter-current to cancel harmonics in real time. Specify from a measured harmonic survey rather than assumption, since sizing depends on the actual spectrum.")
    ]),
    CatalogGroup(id: "terminals", name: "Terminals & Wiring", parts: [
      CatalogPart(id: "phoenix-terminal", manufacturer: "Phoenix", type: "Terminal Block", model: "UK series", rating: "2.5-35mm²", poles: "DIN", curve: "cm rail", about: "Screw-clamp terminal block for field wiring connections. Grouping terminals by function and numbering them consistently is what makes later fault finding fast."),
      CatalogPart(id: "phoenix-ut", manufacturer: "Phoenix", type: "Terminal Block", model: "CLIPLINE UT", rating: "0.14-95mm2", poles: "DIN", curve: "Screw clamp", about: "Screw clamp terminal range covering signal through power cross-sections in a consistent form, with matching bridges, markers and test accessories."),
      CatalogPart(id: "phoenix-pt", manufacturer: "Phoenix", type: "Terminal Block", model: "CLIPLINE PT", rating: "0.14-16mm2", poles: "DIN", curve: "Push-in spring", about: "Push-in spring terminal that accepts a ferruled conductor without a tool, cutting wiring time and removing the retorquing that screw terminals need."),
      CatalogPart(id: "wago-2002", manufacturer: "Generic", type: "Terminal Block", model: "WAGO TOPJOB S", rating: "0.25-16mm2", poles: "DIN", curve: "Push-in CAGE CLAMP", about: "Spring clamp terminal that holds tension regardless of vibration or thermal cycling, which is why it is common on machinery and transport panels."),
      CatalogPart(id: "weidmuller-a", manufacturer: "Generic", type: "Terminal Block", model: "Weidmuller A-series", rating: "0.14-95mm2", poles: "DIN", curve: "Push-in", about: "Push-in terminal system with a uniform accessory set across cross-sections, keeping cross-bridging and marking consistent through the panel."),
      CatalogPart(id: "phoenix-ptfix", manufacturer: "Phoenix", type: "Distribution Block", model: "PTFIX", rating: "1.5-6mm2", poles: "DIN or adhesive", curve: "Potential distributor", about: "Potential distribution block splitting one supply into many outgoing points, tidying up the 24VDC and earth distribution that otherwise turns into daisy-chained terminals."),
      CatalogPart(id: "generic-power-distribution-block", manufacturer: "Generic", type: "Distribution Block", model: "Power distribution block", rating: "125-800A", poles: "1P/3P/4P", curve: "Insulated body", about: "Insulated distribution block taking one large incoming cable and splitting it to several outgoing ways without a full busbar system."),
      CatalogPart(id: "generic-ferrule", manufacturer: "Generic", type: "Ferrule", model: "Bootlace ferrule", rating: "0.5-35mm2", poles: "Per conductor", curve: "Crimped", about: "Bootlace ferrule terminating a stranded conductor so no strand escapes the terminal. Use the correct crimp tool and die, since an under-crimped ferrule becomes a hot joint."),
      CatalogPart(id: "generic-lug", manufacturer: "Generic", type: "Cable Lug", model: "Compression lug", rating: "10-630mm2", poles: "Per conductor", curve: "Crimped", about: "Compression lug terminating large cables onto busbars and breaker pads. Match lug, die and tool from the same system, and confirm bolt torque against the manufacturer figure."),
      CatalogPart(id: "generic-marker", manufacturer: "Generic", type: "Wire Marker", model: "Wire and terminal markers", rating: "All sizes", poles: "Per conductor", curve: "Printed", about: "Printed markers identifying conductors and terminals to the drawing. Consistent numbering is the single thing that most reduces fault-finding time years later."),
      CatalogPart(id: "generic-trunking", manufacturer: "Generic", type: "Trunking", model: "Wiring duct", rating: "Set cm", poles: "PVC", curve: "Slotted", about: "Slotted wiring duct routing and containing panel wiring. Leave real spare capacity, since ducts filled to the brim make later modifications painful and trap heat."),
      CatalogPart(id: "generic-cable-gland", manufacturer: "Generic", type: "Cable Gland", model: "Cable gland", rating: "Set size", poles: "M thread", curve: "IP rated", about: "Cable gland sealing a cable where it enters the enclosure, maintaining the IP rating and providing strain relief. Metal glands additionally terminate cable armour or screen."),
      CatalogPart(id: "generic-din", manufacturer: "Generic", type: "DIN Rail", model: "35mm rail", rating: "1m", poles: "DIN", curve: "Cut to cm", about: "Standard 35mm DIN rail carrying modular devices. Plan rail heights and spacing around wiring duct so devices remain accessible after wiring.")
    ]),
    CatalogGroup(id: "busbars", name: "Busbars & Earthing", parts: [
      CatalogPart(id: "generic-busbar-250", manufacturer: "Generic", type: "Busbar", model: "Copper busbar", rating: "250A", poles: "3P+N", curve: "cm/m sizing", about: "Copper busbar system rated around 250A for distributing current across a board section, keeping outgoing connections short and consistent."),
      CatalogPart(id: "generic-busbar-630", manufacturer: "Generic", type: "Busbar", model: "Copper busbar", rating: "630A", poles: "3P+N", curve: "cm/m sizing", about: "Higher rated busbar for main distribution sections, where cable connections to every outgoing device would be impractical."),
      CatalogPart(id: "rittal-riline", manufacturer: "Rittal", type: "Busbar System", model: "RiLine busbar system", rating: "100-1600A", poles: "3P/4P", curve: "Component adaptor", about: "Busbar system with component adaptors that clip devices directly onto the bars, cutting internal cabling and giving a repeatable, tested arrangement."),
      CatalogPart(id: "generic-copper-bar", manufacturer: "Generic", type: "Copper Bar", model: "Copper bar", rating: "Set cm", poles: "Flat bar", curve: "Busbar", about: "Copper bar carrying current between sections and devices inside the board. Size it for continuous current and short-circuit withstand, and check the support spacing for the fault level."),
      CatalogPart(id: "generic-flexible-busbar", manufacturer: "Generic", type: "Busbar", model: "Flexible braided busbar", rating: "Set A", poles: "Per phase", curve: "Laminated", about: "Flexible laminated connector between busbar and device, absorbing vibration and thermal movement and easing awkward connection geometry."),
      CatalogPart(id: "generic-busbar-support", manufacturer: "Generic", type: "Busbar Support", model: "Busbar support block", rating: "Set A", poles: "3P/4P", curve: "Insulated", about: "Insulated busbar support holding bars at a fixed spacing. Support spacing is a short-circuit withstand question, not a tidiness one: bars must not deflect together under fault forces."),
      CatalogPart(id: "generic-earth-bar", manufacturer: "Generic", type: "Earth Bar", model: "PE bar", rating: "Set length", poles: "PE", curve: "Copper/brass", about: "Protective earth bar giving every circuit a common bonding point. It must be sized for the largest fault current and clearly labelled and accessible."),
      CatalogPart(id: "generic-neutral-bar", manufacturer: "Generic", type: "Neutral Bar", model: "N bar", rating: "Set length", poles: "N", curve: "Copper/brass", about: "Neutral bar collecting circuit neutrals. Keep neutrals grouped with their own circuits so that RCD protection and later fault finding both work predictably."),
      CatalogPart(id: "generic-earth-braid", manufacturer: "Generic", type: "Earth Bonding", model: "Earth bonding braid", rating: "6-25mm2", poles: "Per door", curve: "Flexible", about: "Flexible bonding braid earthing doors and hinged plates. Doors carrying any electrical device must be bonded, and paint has to be removed at the fixing point for the bond to be real.")
    ]),
    CatalogGroup(id: "enclosure", name: "Enclosure & Climate", parts: [
      CatalogPart(id: "rittal-ae", manufacturer: "Rittal", type: "Enclosure", model: "AE compact enclosure", rating: "IP66", poles: "Wall mount", curve: "Sheet steel", about: "Compact wall-mounting enclosure for smaller boards and control panels. Confirm the IP rating survives every cut-out and gland you add to it."),
      CatalogPart(id: "rittal-vx25", manufacturer: "Rittal", type: "Enclosure", model: "VX25 bayed enclosure", rating: "IP55", poles: "Floor standing", curve: "Frame system", about: "Bayable floor-standing frame system for large boards, allowing sections to be joined into a lineup with continuous busbar and shared cable zones."),
      CatalogPart(id: "generic-fan", manufacturer: "Generic", type: "Fan", model: "Panel fan", rating: "230V", poles: "Filter fan", curve: "Airflow", about: "Filter fan drawing cooler outside air through the enclosure to remove heat from drives, transformers and breakers. It needs a matching exit filter, and the filter mats need a cleaning interval in the maintenance plan."),
      CatalogPart(id: "rittal-sk-fan", manufacturer: "Rittal", type: "Fan", model: "SK filter fan", rating: "230V", poles: "Door or side", curve: "Filtered airflow", about: "Filter fan with matched exit filter for forced ventilation. Size airflow from the calculated heat load and remember it can only cool to ambient, never below it."),
      CatalogPart(id: "rittal-bluee", manufacturer: "Rittal", type: "Cooling Unit", model: "Blue e cooling unit", rating: "230/400V", poles: "Wall or roof", curve: "Active cooling", about: "Active cooling unit refrigerating the enclosure below ambient, needed where drives and transformers exceed what filtered ventilation can remove. It needs condensate management and a sealed enclosure to work correctly."),
      CatalogPart(id: "generic-heater", manufacturer: "Generic", type: "Heater", model: "Panel heater", rating: "230V", poles: "DIN", curve: "PTC element", about: "Panel heater preventing condensation in cold or outdoor enclosures. Condensation, not cold, is what damages electronics, so pair it with a hygrostat or thermostat."),
      CatalogPart(id: "generic-thermostat", manufacturer: "Generic", type: "Thermostat", model: "Panel thermostat", rating: "230V", poles: "DIN", curve: "NO/NC", about: "Panel thermostat switching a fan or heater at a set temperature. Use a normally-closed unit for heating and a normally-open unit for cooling."),
      CatalogPart(id: "generic-hygrostat", manufacturer: "Generic", type: "Hygrostat", model: "Panel hygrostat", rating: "230V", poles: "DIN", curve: "Humidity control", about: "Hygrostat switching a heater on humidity rather than temperature, which is the more reliable way to keep an outdoor enclosure dry."),
      CatalogPart(id: "generic-panel-light", manufacturer: "Generic", type: "Panel Light", model: "LED enclosure light", rating: "230V", poles: "Interior", curve: "Door switch", about: "Interior LED light, usually with a door switch, so maintenance inside a deep board does not depend on a hand torch."),
      CatalogPart(id: "generic-panel-socket", manufacturer: "Generic", type: "Socket", model: "Service socket outlet", rating: "230V", poles: "DIN or panel", curve: "16A", about: "Service socket inside the enclosure for test equipment and tools. It should be fed from its own protected circuit with RCD protection."),
      CatalogPart(id: "generic-door-interlock", manufacturer: "Generic", type: "Door Interlock", model: "Door interlock", rating: "Set A", poles: "Handle", curve: "Mechanical", about: "Mechanical door interlock preventing the enclosure being opened while the main switch is closed, with a defeat facility for authorised testing.")
    ]),
    CatalogGroup(id: "door-devices", name: "Door & Operator Devices", parts: [
      CatalogPart(id: "generic-estop", manufacturer: "Generic", type: "Emergency Stop", model: "Emergency stop mushroom", rating: "22/40mm", poles: "NC contacts", curve: "Twist release", about: "Latching emergency stop with positively-driven normally-closed contacts. It must break the control path directly, not merely request a stop from a controller."),
      CatalogPart(id: "generic-push-button", manufacturer: "Generic", type: "Push Button", model: "Push button", rating: "22mm", poles: "NO/NC", curve: "Panel door", about: "22mm door-mounted push button for start, stop and reset commands. Contact blocks are ordered separately, so confirm how many NO and NC contacts each function needs."),
      CatalogPart(id: "generic-door-switch", manufacturer: "Generic", type: "Door Switch", model: "Door position switch", rating: "Set V/A", poles: "NO/NC", curve: "Panel door actuator", about: "Door-position switch used for enclosure lighting, indication or an interlock input. Record the actuator style and contact arrangement; a standard position switch is not automatically a safety-rated guard interlock."),
      CatalogPart(id: "allen-bradley-800f-push-button", manufacturer: "Allen-Bradley", type: "Push Button", model: "800F push button", rating: "22.5mm", poles: "NO/NC blocks", curve: "Momentary or alternate", about: "Allen-Bradley Bulletin 800F push-button operator for a 22.5mm door cut-out. Keep the operator, color, illumination and contact-block arrangement with the exact installed variant."),
      CatalogPart(id: "allen-bradley-800f-selector", manufacturer: "Allen-Bradley", type: "Selector Switch", model: "800F selector switch", rating: "22.5mm", poles: "2/3/4 position", curve: "Maintained or spring return", about: "Allen-Bradley Bulletin 800F selector or key-selector operator. Position count, maintained/spring-return action and contact blocks must match the control scheme."),
      CatalogPart(id: "allen-bradley-800f-pilot-light", manufacturer: "Allen-Bradley", type: "Pilot Light", model: "800F pilot light", rating: "22.5mm", poles: "LED/lamp module", curve: "Voltage and color specific", about: "Allen-Bradley Bulletin 800F pilot-light operator. Record the lens color and the installed LED or lamp-module voltage; the visible operator alone is not a complete orderable assembly."),
      CatalogPart(id: "allen-bradley-800f-estop", manufacturer: "Allen-Bradley", type: "Emergency Stop", model: "800F emergency stop", rating: "22.5mm mounting", poles: "NC contact blocks", curve: "30/40mm operator", about: "Allen-Bradley Bulletin 800F emergency-stop operator. Preserve mushroom size, release method, illumination and positively driven contact arrangement from the drawing or parts schedule."),
      CatalogPart(id: "allen-bradley-800f-contact-block", manufacturer: "Allen-Bradley", type: "Contact Block", model: "800F contact block", rating: "Set V/A", poles: "NO or NC", curve: "Operator accessory", about: "Contact block fitted behind an Allen-Bradley 800F operator. Count it separately only when the drawing or board-specific operator schedule explicitly specifies the installed NO/NC blocks."),
      CatalogPart(id: "allen-bradley-800f-led-module", manufacturer: "Allen-Bradley", type: "Lamp Module", model: "800F LED module", rating: "Set voltage", poles: "Operator module", curve: "Color specific", about: "LED or illumination module fitted behind an Allen-Bradley 800F operator. Voltage and color are stock-defining details and must not be inferred from the operator head alone."),
      CatalogPart(id: "allen-bradley-800t-push-button", manufacturer: "Allen-Bradley", type: "Push Button", model: "800T push button", rating: "30.5mm", poles: "NO/NC blocks", curve: "Oiltight metal operator", about: "Allen-Bradley Bulletin 800T heavy-duty push-button operator for a 30.5mm door cut-out. Record the head style, legend and contact-block arrangement for the installed assembly."),
      CatalogPart(id: "allen-bradley-800t-selector", manufacturer: "Allen-Bradley", type: "Selector Switch", model: "800T selector switch", rating: "30.5mm", poles: "2/3 position", curve: "Maintained or spring return", about: "Allen-Bradley Bulletin 800T heavy-duty selector operator. The position count, key/knob style, return action and contact sequence distinguish the usable variants."),
      CatalogPart(id: "allen-bradley-800t-pilot-light", manufacturer: "Allen-Bradley", type: "Pilot Light", model: "800T pilot light", rating: "30.5mm", poles: "LED/lamp module", curve: "Voltage and color specific", about: "Allen-Bradley Bulletin 800T heavy-duty pilot light. Record lens color, illumination technology and supply voltage exactly; those details are not interchangeable."),
      CatalogPart(id: "allen-bradley-800t-estop", manufacturer: "Allen-Bradley", type: "Emergency Stop", model: "800T emergency stop", rating: "30.5mm mounting", poles: "NC contact blocks", curve: "Heavy-duty mushroom", about: "Allen-Bradley Bulletin 800T emergency-stop operator. Preserve release action, mushroom style and contact arrangement and verify the complete safety function separately."),
      CatalogPart(id: "allen-bradley-802t-door-switch", manufacturer: "Allen-Bradley", type: "Door Switch", model: "802T standard limit switch", rating: "NEMA 4/13", poles: "2/4 circuit", curve: "Lever or push actuator", about: "Allen-Bradley Bulletin 802T oiltight position/limit switch sometimes used to sense an enclosure or machine door. Match the exact actuator and contact action; it is not automatically a safety guard switch."),
      CatalogPart(id: "schneider-xb4", manufacturer: "Schneider", type: "Push Button", model: "Harmony XB4", rating: "22mm", poles: "NO/NC blocks", curve: "Metal bezel", about: "Metal-bezel control station range for doors, with a wide selection of heads and contact blocks that share one mounting cut-out."),
      CatalogPart(id: "siemens-3su1", manufacturer: "Siemens", type: "Push Button", model: "SIRIUS ACT 3SU1", rating: "22mm", poles: "NO/NC blocks", curve: "Plastic or metal", about: "Modular door control range with plastic and metal versions, and connection options from screw terminals to an integrated bus module."),
      CatalogPart(id: "generic-selector", manufacturer: "Generic", type: "Selector Switch", model: "Selector switch", rating: "22mm", poles: "2/3 position", curve: "Panel door", about: "Panel door selector switch giving a positive two or three position choice such as hand-off-auto. Confirm the contact arrangement matches the control logic before drilling the door."),
      CatalogPart(id: "generic-indicator", manufacturer: "Generic", type: "Indicator Light", model: "Pilot light", rating: "24/230V", poles: "22mm", curve: "LED", about: "Pilot light showing run, trip or supply-healthy status on the door. LED versions draw far less current and last longer than filament equivalents."),
      CatalogPart(id: "generic-ammeter", manufacturer: "Generic", type: "Ammeter", model: "Analogue ammeter", rating: "Via CT", poles: "1PH each", curve: "Moving iron", about: "Analogue ammeter giving an at-a-glance load indication on the door. Still favoured on motor panels because a swinging needle shows a struggling load better than a digital readout."),
      CatalogPart(id: "generic-selector-ammeter", manufacturer: "Generic", type: "Selector Switch", model: "Ammeter selector switch", rating: "Via CT", poles: "3PH+off", curve: "Shorting type", about: "Ammeter selector letting one meter read each phase in turn. It must be the CT-shorting type so the transformer secondary is never opened while switching.")
    ])
  ]
}
